kind: Template
apiVersion: v1
metadata:
  name: "registry-console"
  annotations:
    description: "Template for deploying registry web console. Requires cluster-admin."
    tags: infrastructure
labels:
  createdBy: "registry-console-template"
objects:
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: "registry-console"
      labels:
        name: "registry-console"
    spec:
      triggers:
      - type: ConfigChange
      replicas: 1
      selector:
        name: "registry-console"
      template:
        metadata:
          labels:
            name: "registry-console"
        spec:
          containers:
            - name: registry-console
              image: cockpit/kubernetes
              ports:
                - containerPort: 9090
                  protocol: TCP
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /ping
                  port: 9090
                  scheme: HTTP
                initialDelaySeconds: 10
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 5
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /ping
                  port: 9090
                  scheme: HTTP
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 5
              env:
                - name: OPENSHIFT_OAUTH_PROVIDER_URL
                  value: "${OPENSHIFT_OAUTH_PROVIDER_URL}"
                - name: OPENSHIFT_OAUTH_CLIENT_ID
                  value: "${OPENSHIFT_OAUTH_CLIENT_ID}"
                - name: KUBERNETES_INSECURE
                  value: "${KUBERNETES_INSECURE}"
                - name: KUBERNETES_CA_DATA
                  value: "${KUBERNETES_CA_DATA}"
                - name: COCKPIT_KUBE_INSECURE
                  value: "${COCKPIT_KUBE_INSECURE}"
                - name: REGISTRY_ONLY
                  value: "true"
                - name: REGISTRY_HOST
                  value: "${REGISTRY_HOST}"
  - kind: Service
    apiVersion: v1
    metadata:
     name: "registry-console"
     labels:
       name: "registry-console"
    spec:
      type: ClusterIP
      ports:
        - name: registry-console
          protocol: TCP
          port: 9000
          targetPort: 9090
      selector:
        name: "registry-console"
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: registry-console
      annotations:
        description: Atomic Registry console
    spec:
      tags:
        - annotations: null
          from:
            kind: DockerImage
            name: ${IMAGE_NAME}
          name: ${IMAGE_VERSION}
  - kind: OAuthClient
    apiVersion: v1
    metadata:
      name: "${OPENSHIFT_OAUTH_CLIENT_ID}"
      respondWithChallenges: false
    secret: "${OPENSHIFT_OAUTH_CLIENT_SECRET}"
    redirectURIs:
      - "${COCKPIT_KUBE_URL}"
parameters:
  - description: "Container image name"
    name: IMAGE_NAME
    value: "cockpit/kubernetes"
  - description: 'Specify image version; e.g. for "cockpit/kubernetes:latest", set version "latest"'
    name: IMAGE_VERSION
    value: latest
  - description: "The public URL for the Openshift OAuth Provider"
    name: OPENSHIFT_OAUTH_PROVIDER_URL
    required: true
  - description: "The registry console URL, e.g. https://registry-console-default.example.com"
    name: COCKPIT_KUBE_URL
    required: true
  - description: "Console will auto-generate self-signed certificates if secure is false."
    name: COCKPIT_KUBE_INSECURE
    value: "false"
  - description: "Oauth client secret"
    name: OPENSHIFT_OAUTH_CLIENT_SECRET
    from: "user[a-zA-Z0-9]{64}"
    generate: expression
  - description: "Oauth client id"
    name: OPENSHIFT_OAUTH_CLIENT_ID
    value: "cockpit-oauth-client"
  - description: "Skip kubernetes CA verification"
    name: KUBERNETES_INSECURE
    value: "false"
  - description: "PEM Encoded certificate to use for CA verification"
    name: KUBERNETES_CA_DATA
    value: ""
  - description: "The registry route hostname, e.g. registry.example.com"
    name: REGISTRY_HOST
    required: true
